### ISSUE TITLE
Youtube per ID non funziona

### ISSUE THREAD

**Issue by Askancy** [murdercode/laravel-shortcode-plus#72]
Nella documentazione riportate l'esempio di poter usare lo shortcode anche tramite l'id del video, che sinceramente è la scelta più comoda e pure quella logicamente più corretta anziché riportare l'url completo:

```
[youtube id="123456789"]
```
Questo però non funziona, difatti nel file test di YouTubeShortcode usate gli esempi: https://github.com/murdercode/laravel-shortcode-plus/blob/main/tests/YoutubeShortcodeTest.php

infatti richiede l'id del video usando
[youtube url=""]

Tuttavia qui c'é un errore, come potete vedere pure dal test, rimuove la prima lettera dell'id. Se voglio mettere l'ID lFk2cDTqWvw, lui prende Fk2cDTqWvw, esattamente come nel vostro esempio:

```php
it('can parse youtube shortcode, even if the url is incorrect', function () {
    $html = '[youtube url="blablabla"]';
    $youtubeOembed = LaravelShortcodePlus::source($html)->parseAll();
    expect($youtubeOembed)->toContain('https://www.youtube-nocookie.com/embed/lablabla&autoplay=1');
});
```

L'id *b*lablabla diventa lablabla

**Comment by murdercode** [comment]
Ma `[youtube]` non supporta l'attributo `id`. In documentazione è chiaramente specificato che usa solo `url`.
Allo stato attuale usa solo `url`, come da codice:

```php
    public function register($shortcode): string
    {
        $url = $shortcode->url ?? '';
```

**Comment by Askancy** [comment]
Nel readme principale

[youtube id="123456789"]

**Comment by murdercode** [comment]
Ah chiaro, era rimasto come refuso nella prima parte.
La doc sotto in effetti poi era corretta.

Se credi che come feature possa esserti utile puoi:
- Tenere aperta la issue e la valutiamo come feature da aggiungere
- Andare in fork e PR

Nel primo caso non so in che anno riuscirò a farla, per gli improvements invece il merge è sempre aperto :)
